# Generated by Django 5.0.3 on 2024-03-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_task_completed_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
